<html lang="en">
<head>
    <title>Invoice</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <header class="bg-gray-800 text-white py-4 px-6">
        <div class="container mx-auto flex items-center justify-between">
            <!-- University Logo -->
            <div>
                <img src="{{asset('images/sksu.png')}}" alt="University Logo" class="w-24 h-auto">
            </div>
            
            <!-- University Name -->
            <div class="text-center">
                <h1 class="text-2xl font-bold">ISULAN SULAN KUDARATE UNIVERSITY</h1>
                <p class="text-lg mt-1">Medical Report</p>
            </div>
            
            <!-- Contact Information (optional) -->
            <div class="text-right">
                <p class="text-sm">Address: University Address</p>
                <p class="text-sm">Phone: (123) 456-7890</p>
                <p class="text-sm">Email: contact@university.edu</p>
            </div>
        </div>
    </header>
    <div class="container mx-auto p-6 bg-white rounded-lg">

        <!-- Header -->
        <div class="flex items-center justify-between mb-6">
            <div>
                <h1 class="text-3xl font-bold mb-2">Medical Report</h1>
                <p class="text-gray-600">Patient ID: {{ $record->student_unique_id }}</p>
                <p class="text-gray-600">Date of Examination: {{ $record->created_at->format('F j, Y') }}</p>
            </div>
            <div>
                <img src="{{ $record->getUploadImage() }}" alt="Patient Image" class="w-32 h-32 object-cover rounded-full border-2 border-gray-300">
            </div>
        </div>

        <!-- Personal Information -->
        <div class="mb-6">
            <h2 class="text-xl font-semibold mb-4">Personal Information</h2>
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <p class="font-medium">Name:</p>
                    <p>{{ $record->first_name }} {{ $record->middle_name }} {{ $record->last_name }}</p>
                </div>
                <div>
                    <p class="font-medium">Email:</p>
                    <p>{{ $record->email }}</p>
                </div>
                <div>
                    <p class="font-medium">Age:</p>
                    <p>{{ $record->age }}</p>
                </div>
                <div>
                    <p class="font-medium">Date of Birth:</p>
                    <p>{{ $record->birthDateFormat() }}</p>
                </div>
                <div>
                    <p class="font-medium">Address:</p>
                    <p>{{ $record->address }}</p>
                </div>
                <div>
                    <p class="font-medium">Civil Status:</p>
                    <p>{{ $record->civil_status }}</p>
                </div>
            </div>
        </div>

        <!-- Medical Details -->
        <div class="mb-6">
            <h2 class="text-xl font-semibold mb-4">Medical Details</h2>
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <p class="font-medium">Past Illness:</p>
                    <p>{{ $record->past_illness }}</p>
                </div>
                <div>
                    <p class="font-medium">Allergies:</p>
                    <p>{{ $record->allergies }}</p>
                </div>
                <div>
                    <p class="font-medium">Temperature:</p>
                    <p>{{ $record->temperature }} °C</p>
                </div>
                <div>
                    <p class="font-medium">Blood Pressure:</p>
                    <p>{{ $record->systolic_pressure }}/{{ $record->diastolic_pressure }} mmHg</p>
                </div>
                <div>
                    <p class="font-medium">Heart Rate:</p>
                    <p>{{ $record->heart_rate }} bpm</p>
                </div>
                <div>
                    <p class="font-medium">Diagnoses:</p>
                    <p>{{ $record->diagnoses }}</p>
                </div>
                <div>
                    <p class="font-medium">Remarks:</p>
                    <p>{{ $record->remarks }}</p>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <div class="text-center text-gray-600 mt-8">
            <p>Report Generated by {{ $record->physician_name }}</p>
            <p>Release By: {{ $record->release_by }}</p>
        </div>
    </div>

</body>
</html>